### PR TITLE
Updated to work with nYNAB and updated readme.

### PR DESCRIPTION
**Pull request by aon**
Almost everything should be working. It's missing transactions, imported bank transactions and the web app to talk to ynab's api.

### CODE REVIEW

**Comment by aon** [comment]
So I've tried to work on subtransactions, but there's something that concerns me. YNAB lets you choose different payees for each subtransaction and it lets you choose different transfer payees for each. How could we go about moving this to Actual without losing data in the process?

**Comment by jlongster** [comment]
Wow, this is awesome, thank you so much!

I am SO sorry I've been late responding to this. I've been heads down finishing the next release that will come out this weekend that is a big refactoring. I'm going to take a close look at this this weekend.

**Comment by jaltek** [comment]
Just am small feedback on this. I tried @aon 's test branch and it worked FMPOV very well. I was using https://github.com/ksmithbaylor/ynab-json-exporter for a json export of my budget - so the only thing I had to change was 
```data.data.budget.name``` and ```data.data.budget``` 
into
```data.budget.name``` and ```data.budget``` 
at
https://github.com/aon/import-ynab5/blob/e194480606a6951f76922366ed27a8137b353333/importer.js#L313

**Comment by jlongster** [comment]
I have had this tab open for a while to respond. I'm so sorry @aon, I have no excuse, this repo was just stuck on the backlog.

About payees in child transactions, that is currently something that Actual doesn't support. You have the same data loss when importing YNAB4. Luckily it doesn't effect any of the budget or account balances, but you just lose that data. Everything should still be in tact though.

I'm going to fix this, but I don't have an ETA yet.

@jaltek that's great to hear!

**Comment by aon** [comment]
Hey @jaltek that's awesome! In the future it should automatically get the JSON dump from the YNAB api itself, never got around to actually doing that part.

Don't worry @jlongster!

**Comment by jaltek** [comment]
> Hey @jaltek that's awesome! In the future it should automatically get the JSON dump from the YNAB api itself, never got around to actually doing that part.

Maybe I can find the time here to bring them both together...both are already very good approaches.

**Comment by jaltek** [comment]
@aon If I see this correctly, "split transactions" doesn't work either yet, right?
Or did you mean that with "subtransactions"?

In my case all of the entries with split transactions got an empty category...

**Comment by aon** [comment]
Yes! That's what I meant, split transactions. I called it subtransactions because that's what the YNAB api calls it https://api.youneedabudget.com/v1

And yeah, in ynab you can have each subtransaction with a different category and payee. I think in actual you can only have different payee though I'm not sure. Maybe it could be set up so that each subtransaction becomes one transaction and write under notes that it belonged to a subtransaction?

**Comment by jaltek** [comment]
That would be one possibility, but then again it could lead to confusion if you compare the individual amounts with your credit card statement, for example. The advantage of these transactions is that the total is always the same, but divided into different categories.
I would almost say that I don't care about the payee inside the split transactions. The important thing is that the individual amounts end up in the right categories, right?

This is how Actual already does it:

**Comment by aon** [comment]
Ohhhh ok, I thought actual only let you choose one category for the whole transaction and then a payee for each subtransaction, but it was the other way around. Totally, I agree with you, payees wouldn't really matter as long as the budget stays ok.

**Comment by MikeBishop** [comment]
> Totally, I agree with you, payees wouldn't really matter as long as the budget stays ok.

...unless the subtransaction is a transfer.  (Which YNAB UI reflects in the Payee field; don't know about the XML.)  It seems like you'd have the least data loss in that case to just import them as separate transactions.

**Comment by jlongster** [comment]
Just want to reiterate -- thanks so much for having this ready, merged in these changes in the other PR which includes these.

Sadly Actual doesn't support payees/transfers in subtransactions yet, but it should. You shouldn't have data loss though, it's just the transactions won't be "connected" as transfers. For the specific individual account, it would still have that transaction recorded.

**Pull request merged**
